"""add mobile number

Revision ID: 268d55c084cf
Revises: 9d0be6640444
Create Date: 2026-07-14 19:53:43.960949
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import backend

revision: str = '268d55c084cf'
down_revision: Union[str, None] = '9d0be6640444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lawyer_profiles', sa.Column('mobile_number', backend.models.EncryptedString(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lawyer_profiles', 'mobile_number')
    # ### end Alembic commands ###
