"""add phonepe_transaction_id

Revision ID: 80394484e25e
Revises: 268d55c084cf
Create Date: 2026-07-20 12:28:01.447277
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '80394484e25e'
down_revision: Union[str, None] = '268d55c084cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('phonepe_transaction_id', sa.String(length=255), nullable=True))
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_bookings_phonepe_transaction_id', ['phonepe_transaction_id'])
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('uq_bookings_phonepe_transaction_id', type_='unique')
    op.drop_column('bookings', 'phonepe_transaction_id')
    # ### end Alembic commands ###
