"""add_cancellation_fields_and_vouchers

Revision ID: 9b17288bd3cf
Revises: 80394484e25e
Create Date: 2026-08-07 12:11:13.573521
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import backend.models

revision: str = '9b17288bd3cf'
down_revision: Union[str, None] = '80394484e25e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('dispute_category',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('disputed_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('lawyer_duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('client_duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('auto_resolution_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)

    with op.batch_alter_table('draft_comments', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
        batch_op.alter_column('page_number',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('position_x',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('position_y',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_draft_comments_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_draft_comments_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('drafting_requests', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.Enum('OPEN', 'PENDING_PAYMENT', 'IN_PROGRESS', 'SUBMITTED', 'REVISION_REQUESTED', 'COMPLETED', 'CANCELLED', name='draftingstatus'),
               existing_nullable=False)
        batch_op.alter_column('draft_file_key',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('draft_filename',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('documents',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))

    with op.batch_alter_table('lawyer_bank_accounts', schema=None) as batch_op:
        batch_op.alter_column('ifsc_code',
               existing_type=sa.VARCHAR(length=11),
               type_=backend.models.EncryptedString(),
               existing_nullable=False)

    with op.batch_alter_table('lawyer_profiles', schema=None) as batch_op:
        batch_op.alter_column('practice',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('aadhaar_number',
               existing_type=sa.VARCHAR(length=100),
               type_=backend.models.EncryptedString(),
               existing_nullable=True)
        batch_op.alter_column('practice_address',
               existing_type=sa.VARCHAR(length=255),
               type_=backend.models.EncryptedString(),
               existing_nullable=True)
        batch_op.alter_column('bar_license_url',
               existing_type=sa.VARCHAR(length=255),
               type_=backend.models.EncryptedString(),
               existing_nullable=True)
        batch_op.alter_column('aadhaar_url',
               existing_type=sa.VARCHAR(length=255),
               type_=backend.models.EncryptedString(),
               existing_nullable=True)
        batch_op.alter_column('strike_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.drop_index(batch_op.f('ix_lawyer_profiles_practice'))
        batch_op.create_index(batch_op.f('ix_lawyer_profiles_verification_status'), ['verification_status'], unique=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lawyer_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lawyer_profiles_verification_status'))
        batch_op.create_index(batch_op.f('ix_lawyer_profiles_practice'), ['practice'], unique=False)
        batch_op.alter_column('strike_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('aadhaar_url',
               existing_type=backend.models.EncryptedString(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('bar_license_url',
               existing_type=backend.models.EncryptedString(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('practice_address',
               existing_type=backend.models.EncryptedString(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('aadhaar_number',
               existing_type=backend.models.EncryptedString(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('practice',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    with op.batch_alter_table('lawyer_bank_accounts', schema=None) as batch_op:
        batch_op.alter_column('ifsc_code',
               existing_type=backend.models.EncryptedString(),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    with op.batch_alter_table('drafting_requests', schema=None) as batch_op:
        batch_op.alter_column('documents',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
        batch_op.alter_column('draft_filename',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('draft_file_key',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.Enum('OPEN', 'PENDING_PAYMENT', 'IN_PROGRESS', 'SUBMITTED', 'REVISION_REQUESTED', 'COMPLETED', 'CANCELLED', name='draftingstatus'),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)

    with op.batch_alter_table('draft_comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_draft_comments_user_id'))
        batch_op.drop_index(batch_op.f('ix_draft_comments_request_id'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('position_y',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('position_x',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('page_number',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('auto_resolution_status',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('client_duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('lawyer_duration_seconds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('disputed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('dispute_category',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
