"""add_aadhaar_and_profile_picture

Revision ID: 9d0be6640444
Revises: 8dcb01bed07f
Create Date: 2026-07-02 11:22:48.175019
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = '9d0be6640444'
down_revision: Union[str, None] = '8dcb01bed07f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lawyer_profiles', sa.Column('aadhaar_number', sa.String(length=100), nullable=True))
    op.add_column('lawyer_profiles', sa.Column('profile_picture_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lawyer_profiles', 'profile_picture_url')
    op.drop_column('lawyer_profiles', 'aadhaar_number')
    # ### end Alembic commands ###
